== Q
How many arguments does the command `git config --global --add user.name My user name` contain?

. 0
. 1
. 2
. 3
. 4
. 5
. 6
. [true-claim] 7
. 8
. 9
. 10
. 11
. 12

== Q
If the relative path `../c/` (relative to your current directory) designates the directory `/a/b/c/`, then which of the following paths possibly refer to your current directory?

. `/`
. `/a/`
. `/a/../`
. `/a/../c/`
. `/a/b/`
. `/a/b/../`
. [true-claim] `/a/b/c/`
. [true-claim] `/a/b/c/../c/`
. [true-claim] `/a/b/c/../d/`
. `/a/b/c/a/`
. [true-claim] `/a/b/c/a/../`
. `/a/b/c/a/../c/`
. `/a/b/c/d/`
. `/a/c/../c/`
. `/a/c/../d/`

== Q
Which _relative_ paths, relative to `/a/b/c/`, permit to designate the path `/a/b/c/d/e/`?

. `/a/b/c/`
. `/a/b/c/d/e/`
. `/a/b/c/ /d/e/`
. `/a/b/d/e/`
. `/a/b/../c/d/e/`
. `/d/e/`
. `/d/e/a/b/c/`
. `/../c/d/e/`
. `/d/e/`
. `/d/../d/e/`
. `/d/e/../a/b/c/d/e/`
. `a/b/c/`
. `a/b/c/d/e/`
. `a/b/c/ /d/e/`
. `a/b/d/e/`
. `a/b/../c/d/e/`
. [true-claim] `d/e/`
. `d/e/a/b/c/`
. [true-claim] `../c/d/e/`
. [true-claim] `d/e/`
. [true-claim] `d/../d/e/`
. `d/e/../a/b/c/d/e/`

== Q
Check every true claim, related to the structure of commits in a git repository.

. The structure is never a list, independently of the repository
. [true-claim] The structure _may_ or may _not_ be a list, depending on the repository
. The structure is guaranteed to be a list, independently of the repository
. The structure is never a tree, independently of the repository
. [true-claim] The structure _may_ or may _not_ be a tree, depending on the repository
. The structure is guaranteed to be a tree, independently of the repository
. The structure is never a directed graph, independently of the repository
. The structure _may_ or may _not_ be a directed graph, depending on the repository
. [true-claim] The structure is guaranteed to be a directed graph, independently of the repository
. The structure is never a directed acyclic graph, independently of the repository
. The structure _may_ or may _not_ be a directed acyclic graph, depending on the repository
. [true-claim] The structure is guaranteed to be a directed acyclic graph, independently of the repository
. [true-claim] The structure never contains directed cycles, independently of the repository
. The structure _may_ or may _not_ contain directed cycles, depending on the repository
. The structure is guaranteed to contain directed cycles, independently of the repository

== Q
Assume that your git repository currently contains a commit `c` having a parent commit `b`, itself having a parent `a` (so that `a` was the first commit in your git repository). A branch `main` points to `b` and a branch `dev` points to `c`. The git-ref `HEAD` points to `main`. Assume that your index is not empty. Assume that you now commit. What results? Check every true claim.

. `HEAD` points to `a`
. `HEAD` points to `b`
. `HEAD` points to `c`
. [true-claim] `HEAD` still points to `main`
. `HEAD` points to `dev`
. `HEAD` points to a new commit having `a` as parent
. `HEAD` points to a new commit having `b` as parent
. `HEAD` points to a new commit having `c` as parent
. `HEAD` is  “detached”
. `main` points to `a`
. `main` still points to `b`
. `main` points to `c`
. `main` points to `dev`
. `main` points to `HEAD`
. `main` points to a new commit having `a` as parent
. [true-claim] `main` points to a new commit having `b` as parent
. `main` points to a new commit having `c` as parent
. `dev` points to `a`
. `dev` points to `b`
. [true-claim] `dev` still points to `c`
. `dev` points to `main`
. `dev` points to `HEAD`
. `dev` points to a new commit having `a` as parent
. `dev` points to a new commit having `b` as parent
. `dev` points to a new commit having `c` as parent
