== Q
How many arguments does the command `ls -l --directory "-A" "../a/b c" "b c" b c` contain?

. 0
. 1
. 2
. 3
. 4
. 5
. 6
. [true-claim] 7
. 8
. 9
. 10
. 11
. 12

== Q
Relative to the directory `/a/b/c/`, which file is designated by the relative path `../d/../e/./f`?

. `/`
. `/a`
. `/a/b/c/d/e/f`
. `/a/b/c/f`
. `/a/b/d/f`
. [true-claim] `/a/b/e/f`
. `/a/c/d/f`
. `/a/c/d/e/f`
. `/a/c/d/e/e/f`
. `/b/a/d/e/f`
. `/b/a/d/e/e/f`
. `/b/a/d/f`
. `/b/c/d/e/f`
. `/b/c/d/e/e/f`
. `/b/c/d/f/e`
. `/b/c/d/f/f/e`
. `/b/d/f`
. `/b/d/e/f`
. `/b/d/e/e/f`
. `/d/e/f`
. `/d/f/e`
. `/e/f`
. `/e/e/f`
. `/f/e`

== Q
Assuming that your current directory is `/a/b/c/`, which directory does the absolute path `/d/e/` designate?

. `/a/b/c/`
. `/a/b/c/d/e/`
. `/a/b/c/ /d/e/`
. `/a/b/d/e/`
. [true-claim] `/d/e/`
. `/d/e/a/b/c/`

== Q
What are the “git refs” that we have met in this course (such as `HEAD`, for example)? (Check every correct claim.)

. A node in the graph of commits
. A node in the DAG of commits
. A node in the tree of commits
. A pointer to a node in the graph of commits
. A named pointer to a node in the DAG of commits
. A named pointer to a node in the tree of commits
. A named pointer to a commit
. A named pointer to a branch
. A named pointer to a branch or a commit
. A named pointer to a git ref
. A named pointer to a git ref or to a branch
. A named pointer to a git ref or to a commit
. [true-claim] A named pointer to a git ref or to a branch or to a commit

== Q
Assume that `HEAD` “contains” a blob about “file1”, your workspace contains “file1” (with the same content) and “file2” (with nonempty content), and your index is empty. Assume you now commit. What does `HEAD` contain as a result?

. Nothing
. A single blob about “file1”, as previously
. Duplicated blobs about “file1”
. Two blobs, one about “file1” and one about “file2”

== Q
Assume that your current branch is `somebranch`, your current commit is `C0`. Assume that you execute the command `git commit`, resulting in a new commit `C1`; then the command `git branch newbranch`; then `git checkout C0`. What is the commit now associated to `newbranch`?

. None
. `C0`
. [true-claim] `C1`
. Both `C0` and `C1`
. `HEAD`
. The index
